
---
spring:
  jpa:
    generate-ddl: true        
        
---
spring:
  profiles: db2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect

---
spring:
  profiles: sqlserver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
